### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by prologic** [walchko/netscan2#2]
Looking forward to being able to ``pip install netscan`` :)

**Comment by walchko** [comment]
I fixed a couple issues, but I can't seem to get the new version on pypi for some reason ... not sure why. Only the first version is showing ... frustrating :(

**Comment by prologic** [comment]
Did you bump the version? What's the output from ``python setup.py bdist_wheel register upload``? :)

**Comment by walchko** [comment]
crap ... I just found a typo in my .pypirc file ... I use twine to encrypt my connection. Strange it worked the first time (yesterday), but not today. It should work now, it does on OSX and my RPi.
